server:
  address: tcp://0.0.0.0:9091

log:
  level: info

identity_validation:
  reset_password:
    jwt_secret: "h9dGbzE+PvMKY7bTn3rL8VnccgoX7iGuh0ptcBBA0NM="

authentication_backend:
  file:
    path: /config/users.yml

access_control:
  default_policy: deny
  rules:
    - domain: gitea.localdomain.com
      policy: one_factor
    - domain: grafana.localdomain.com
      policy: one_factor

session:
  name: authelia_session
  secret: "zWzjHtkLo5I6r7W6qlB52YknyZLrAw5+vECdZuMaKcE="
  expiration: 3600
  cookies:
    - domain: localdomain.com
      authelia_url: https://auth.localdomain.com
      default_redirection_url: https://gitea.localdomain.com
# session:
#   name: authelia_session
#   secret: "your-random-secret"
#   expiration: 3600
#   cookies:
#     - domain: gitea.localdomain.com
#       authelia_url: https://auth.localdomain.com
#       default_redirection_url: https://gitea.localdomain.com

#     - domain: grafana.localdomain.com
#       authelia_url: https://auth.localdomain.com
#       default_redirection_url: https://grafana.localdomain.com


storage:
  local:
    path: /config/db.sqlite3
  encryption_key: "YBfzH3oOwR7AeE8QZEnmnQGdeu+H8rhlsmVG8VjRMVw="

notifier:
  filesystem:
    filename: /config/notification.txt
